// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCG2W3S-G3nek5iQFN5b5ZGXaJFctPJ20',
    appId: '1:460112407414:web:197d3bcfcfc912ec7be857',
    messagingSenderId: '460112407414',
    projectId: 'liveasy-2000',
    authDomain: 'liveasy-2000.firebaseapp.com',
    storageBucket: 'liveasy-2000.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw4yK0_3TnOxmemrP47zz3syPcPLTcl7U',
    appId: '1:460112407414:android:487bd48b947919357be857',
    messagingSenderId: '460112407414',
    projectId: 'liveasy-2000',
    storageBucket: 'liveasy-2000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASygRIiDNtBQoY2SHL0VqcCA1-wYxtDL4',
    appId: '1:460112407414:ios:c2a293a7d669b0ff7be857',
    messagingSenderId: '460112407414',
    projectId: 'liveasy-2000',
    storageBucket: 'liveasy-2000.appspot.com',
    iosClientId: '460112407414-fread8jkulmunh2m8ihf77ohchduejud.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASygRIiDNtBQoY2SHL0VqcCA1-wYxtDL4',
    appId: '1:460112407414:ios:c2a293a7d669b0ff7be857',
    messagingSenderId: '460112407414',
    projectId: 'liveasy-2000',
    storageBucket: 'liveasy-2000.appspot.com',
    iosClientId: '460112407414-fread8jkulmunh2m8ihf77ohchduejud.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveasy',
  );
}
